### ISSUE TITLE
Change pluginNameWithRevision?

### ISSUE THREAD

**Issue by scurest** [Luctaris/GLideN64-SceneRipper#1]
It's pretty hard to tell the plugin apart from regular GLideN64 in the plugin list

![](https://user-images.githubusercontent.com/11024420/216451896-7e01fc11-80fe-45df-b58d-1300ff70f85f.png)

Could it be renamed "Luctaris's GLideN64" or something?

**Comment by theanine3D** [comment]
+1. I had this issue as well.

**Comment by Luctaris** [comment]
Already addressed locally, but haven't pushed new code yet. Scheduled to be renamed to "GlideN64 Sceneripper rev.XXXXXXXX"
